- database/migrations/2017_03_29_000000_avored_framework_schema.php
- src/AdminConfiguration/AdminConfiguration.php
- src/AdminConfiguration/AdminConfigurationGroup.php
- src/AdminConfiguration/Contracts/AdminConfiguration.php
- src/AdminConfiguration/Contracts/DropdownFieldContract.php
- src/Models/Database/Order.php
- src/Models/Database/Product.php
> mergin dev to master 

- resources/views/order/view.blade.php
Fixed https://github.com/avored/laravel-ecommerce/issues/189
> Fixed dropdown align

- resources/assets/sass/_custom.scss
- resources/views/layouts/left-nav.blade.php
Fix for https://github.com/avored/laravel-ecommerce/issues/11
> Fixed default logo

- resources/views/datagrid/grid.blade.php
@indpurvesh this is a initial progress on switching the datagrid from divs to tables.
> Fix avored/laravel-ecommerce#219

- database/migrations/2017_03_29_000000_avored_framework_schema.php
- resources/lang/en/lang.php
- resources/lang/en/orders.php
- resources/views/order/return-request/index.blade.php
- resources/views/order/return-request/view.blade.php
- resources/views/order/view.blade.php
- routes/web.php
- src/AdminMenu/AdminMenuProvider.php
- src/DataGrid/Manager.php
- src/Models/Contracts/OrderReturnProductInterface.php
- src/Models/Contracts/OrderReturnRequestInterface.php
- src/Models/Database/Order.php
- src/Models/Database/OrderReturnProduct.php
- src/Models/Database/OrderReturnRequest.php
- src/Models/Database/Product.php
- src/Models/ModelProvider.php
- src/Models/Repository/OrderReturnProductRepository.php
- src/Models/Repository/OrderReturnRequestRepository.php
- src/Order/Controllers/OrderReturnRequestController.php
- src/Order/DataGrid/OrderReturnRequestDataGrid.php
> Order return

- database/migrations/2017_03_29_000000_avored_framework_schema.php
- resources/lang/en/product.php
- resources/views/product/property/_fields.blade.php
- src/Models/Database/Property.php
- src/System/Controllers/DashboardController.php
\
Added an is_visible_frontend field into a property table
> added another field into properties 

- src/Cart/Manager.php
> Cart Manager should return price formatted #254

- src/Theme/Provider.php
> Fixed DB Connection Check

- database/factories/AddressFactory.php
- database/factories/PageFactory.php
- database/factories/ProductFactory.php
- database/factories/WishlistFactory.php
- database/migrations/2017_03_29_000000_avored_framework_schema.php
- resources/views/system/tax-rate/_fields.blade.php
- src/Models/Repository/CategoryRepository.php
- src/Product/Controllers/ProductController.php
- src/System/Controllers/TaxRateController.php
- src/System/Requests/TaxRateRequest.php
- src/Theme/Provider.php
- tests/Controller/ProductTest.php
> merging dev to master 

- composer.json
> Laravel6 support 

- .styleci.yml
Add PHP only copy of Laravel Framework [StyleCI](https://styleci.io/) config.
> Add PHP StyleCI config

- .gitignore
Add a very basic .gitignore file.
> Add basic .gitignore

- routes/web.php
- src/Catalog/Controllers/AttributeController.php
- src/Catalog/Controllers/CategoryController.php
- src/Catalog/Controllers/PropertyController.php
- src/Cms/Controllers/PageController.php
- src/Database/Repository/CategoryRepository.php
- src/Modules/Console/ControllerMakeCommand.php
- src/Modules/Console/ModuleMakeCommand.php
- src/Order/Controllers/OrderStatusController.php
- src/Permission/Manager.php
- src/Support/Console/AdminMakeCommand.php
- src/Support/Console/InstallCommand.php
- src/Support/Providers/MenuProvider.php
- src/Support/Providers/ModuleProvider.php
- src/Support/Providers/TabProvider.php
- src/System/Controllers/CurrencyController.php
- src/System/Controllers/LanguageController.php
- src/System/Controllers/RoleController.php
- src/System/Controllers/StateController.php
- src/User/Controllers/AdminUserController.php
- src/User/Controllers/UserGroupController.php
Removed some unused variables and string concats, remove assign in if condition, use short list syntax and more.
> Simple code cleanup

- README.md
Before:
<p>
<a href="https://circleci.com/gh/avored/framework/tree/master"><img src="https://circleci.com/gh/avored/framework/tree/master.svg" alt="CircleCI"></a>
<a href="https://packagist.org/packages/avored/framework"><img src="https://poser.pugx.org/avored/framework/downloads" alt="Total Downloads"></a>
<a href="https://packagist.org/packages/avored/framework"><img src="https://poser.pugx.org/avored/framework/v/stable" alt="Latest Stable Version"></a>
<a href="https://packagist.org/packages/avored/framework"><img src="https://poser.pugx.org/avored/framework/license" alt="License"></a>
</p>
After:
<p>
<a href="https://circleci.com/gh/avored/framework/tree/master"><img src="https://circleci.com/gh/avored/framework/tree/master.svg?style=shield" alt="CircleCI"></a>
<a …
> Update CircleCI badge for consistent styling

- src/Breadcrumb/Builder.php
- src/Catalog/Controllers/AttributeController.php
- src/Catalog/Controllers/CategoryController.php
- src/Catalog/Controllers/ProductController.php
- src/Catalog/Controllers/PropertyController.php
- src/Cms/Controllers/MenuGroupController.php
- src/Cms/Controllers/PageController.php
- src/Order/Controllers/OrderController.php
- src/Order/Controllers/OrderStatusController.php
- src/System/Controllers/CurrencyController.php
- src/System/Controllers/LanguageController.php
- src/System/Controllers/RoleController.php
- src/System/Controllers/StateController.php
- src/System/Controllers/TaxGroupController.php
- src/System/Controllers/TaxRateController.php
- src/User/Controllers/AdminUserController.php
- src/User/Controllers/UserGroupController.php
> Use compact() when passing view data

- phpunit.xml
- tests/BaseTestCase.php
- tests/Controllers/AdminUserTest.php
- tests/Controllers/AttributeTest.php
- tests/Controllers/AuthTest.php
- tests/Controllers/CategoryTest.php
- tests/Controllers/ConfigurationTest.php
- tests/Controllers/CurrencyTest.php
- tests/Controllers/LanguageTest.php
- tests/Controllers/MenuTest.php
- tests/Controllers/OrderStatusTest.php
- tests/Controllers/PageTest.php
- tests/Controllers/ProductTest.php
- tests/Controllers/PropertyTest.php
- tests/Controllers/RoleTest.php
- tests/Controllers/StateTest.php
- tests/Controllers/TaxGroupTest.php
- tests/Controllers/TaxRateTest.php
- tests/Controllers/UserGroupTest.php
- tests/Functional/BreadcrumbTest.php
- tests/Functional/UserTest.php
Tests code cleanup in preparation for permission testing.
> Tests cleanup

- tests/Integration/PermissionTest.php
Add test to check if an user without permission is unauthorized.
> Add Permission test

- .github/workflows/avored-test.yml
> Indpurvesh patch 2

- package.json
- resources/components/order/order/OrderTable.vue
- resources/js/services/components.js
- resources/views/layouts/app.blade.php
- resources/views/order/order/invoice.blade.php
- resources/views/order/order/shipping-label.blade.php
- src/Database/Models/Address.php
- src/Database/Models/Customer.php
- src/Database/Models/Order.php
- src/Order/Controllers/OrderController.php
- src/Support/Console/InstallCommand.php
- yarn.lock
> few changes

- src/Support/Console/InstallCommand.php
> Bug fixed issue #472

- database/factories/AdminUserFactory.php
AdminUserFactory class containing plain text password. It leads to the error that cannot log in using the generated user credentials.
> admin user factory fix

- README.md
- composer.json
Remove www prefix from all links on README.md and composer.json
> Fix avored.com links: hacktoberfest

- tests/unit/ProductTest.php
Add unit test for format price
> Add unit test for format price

- config/avored.php
- resources/components/catalog/category/CategoryTable.vue
- resources/js/modules/system/lang/en.json
- src/Catalog/Controllers/CategoryController.php
- src/Database/Models/Category.php
Added a Parent ID into Category table
> Added a parent id into category table

- src/AvoRedProvider.php
- src/Support/Providers/BladeProvider.php
[https://github.com/avored/laravel-ecommerce/issues/514](url)
> Currency blade directive #514

- resources/views/catalog/product/cards/attribute.blade.php
- src/Database/Models/Product.php
> fixed the variation product do not show in product list

- resources/components/order/order/OrderShow.vue
- resources/views/order/order/show.blade.php
- src/AvoRedProvider.php
- src/Menu/MenuProvider.php
> fixed the order comment css

- src/Graphql/Queries/AddressQuery.php
- src/Graphql/Queries/AllAddressQuery.php
- src/Graphql/Queries/AllCategoryQuery.php
- src/Graphql/Queries/AllOrdersQuery.php
- src/Graphql/Queries/CartItemsQuery.php
- src/Graphql/Queries/CategoryQuery.php
- src/Graphql/Queries/CountryOptionsQuery.php
- src/Graphql/Queries/CustomerQuery.php
- src/Graphql/Queries/LatestProductQuery.php
- src/Graphql/Queries/OrderQuery.php
- src/Graphql/Queries/PaymentQuery.php
- src/Graphql/Queries/ProductQuery.php
- src/Graphql/Queries/ShippingQuery.php
- src/Graphql/Types/NotificationType.php
- src/Graphql/Types/OptionType.php
- src/Graphql/Types/PaymentType.php
- src/Graphql/Types/ShippingType.php
- src/Graphql/Types/SubscriberType.php
about issue:  https://github.com/avored/laravel-ecommerce/issues/626
> Initial letter size adjustment

- resources/lang/en/system.php
- resources/views/catalog/attribute/index.blade.php
- resources/views/catalog/product/cards/images.blade.php
- routes/web.php
- src/Catalog/Controllers/ProductController.php
- src/Database/Models/Product.php
Fixed the front end alpine js component and backend product image delete feather added too.
> Fixed the backend delete product images and frontend alpine js component

- resources/lang/en/system.php
- resources/views/catalog/product/cards/images.blade.php
Fixed the image height issue and remove the hardcoded product id it was for testing purpose which left out.
> fixed the images height issue and make the product id dynamic
